import { Stack, StackProps, RemovalPolicy } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as iam from 'aws-cdk-lib/aws-iam';

export class EC2Stack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    // IAM 역할 및 인스턴스 프로파일 생성
    const instanceRole = new iam.Role(this, 'InstanceRole', {
      assumedBy: new iam.ServicePrincipal('ec2.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('AdministratorAccess'),
      ],
    });
    // const instanceProfile = new iam.CfnInstanceProfile(this, 'InstanceProfile', {
    //   roles: [instanceRole.roleName],
    //   instanceProfileName: 'myInstanceProfile',
    // });

    const defaultVpc = ec2.Vpc.fromLookup(this, 'VPC', {
      isDefault: true,
    });

    const chatbotAppSecurityGroup = new ec2.SecurityGroup(this, 'chatbotAppSecurityGroup', {
      vpc: defaultVpc,
    });
    chatbotAppSecurityGroup.addIngressRule(
      ec2.Peer.anyIpv4(),
      ec2.Port.tcp(80),
      'httpIpv4',
    );
    chatbotAppSecurityGroup.addIngressRule(
      ec2.Peer.anyIpv4(),
      ec2.Port.tcp(22),
      'sshIpv4',
    );

    const machineImage = ec2.MachineImage.fromSsmParameter(
      '/aws/service/canonical/ubuntu/server/focal/stable/current/amd64/hvm/ebs-gp2/ami-id'
    );
    
    const userData = ec2.UserData.forLinux();
    userData.addCommands(
      'sudo apt-get update -y',
      'sleep 15',
      'sudo apt-get install ec2-instance-connect && sleep 15',
      'sudo apt install -y git && sleep 15',
      'sudo apt install -y python3-pip && sleep 20',
      'sudo apt install -y python3.8-venv && sleep 20',
      'cd /home/ubuntu && sudo git clone https://github.com/ottlseo/advanced-rag-workshop.git',
      'sudo python3 -m venv --copies /home/ubuntu/my_env',
      'sudo chown -R ubuntu:ubuntu /home/ubuntu/my_env',
      'source /home/ubuntu/my_env/bin/activate',
      'sleep 15',
      'cd advanced-rag-workshop/application',
      'pip3 install -r requirements.txt && sleep 180',
      'pip3 install -U langchain-community && sleep 20',
      'cat <<EOF > /etc/systemd/system/streamlit.service',
      '[Unit]',
      'Description=Streamlit App',
      'After=network.target',
      '',
      '[Service]',
      'User=ubuntu',
      'Environment="AWS_DEFAULT_REGION=us-west-2"',
      'WorkingDirectory=/home/ubuntu/advanced-rag-workshop/application',
      'ExecStartPre=/bin/bash -c "sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8501"',
      'ExecStart=/bin/bash -c "source /home/ubuntu/my_env/bin/activate && streamlit run streamlit.py --server.port 8501"',
      'Restart=always',
      '',
      '[Install]',
      'WantedBy=multi-user.target',
      'EOF',
      'sudo systemctl daemon-reload',
      'sudo systemctl enable streamlit',
      'sudo systemctl start streamlit',
    );
    
    // EC2 인스턴스 생성
    const chatbotAppInstance = new ec2.Instance(this, 'chatbotAppInstance', {
      instanceType: new ec2.InstanceType('m5.large'),
      machineImage: machineImage,
      vpc: defaultVpc,
      securityGroup: chatbotAppSecurityGroup,
      role: instanceRole,
      userData: userData,
    });

    const chatbotAppUrl = new cdk.CfnOutput(this, 'chatbotAppUrl', {
      value: `http://${chatbotAppInstance.instancePublicIp}/`,
      description: 'The URL of chatbot instance generated by AWS Advanced RAG Workshop',
      exportName: 'chatbotAppUrl',
    })
  }
}
